apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment
  namespace: daffodil
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: java-microservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-microservice
    spec:
      containers:
      - name: java-microservice-container
        image: 870033244562.dkr.ecr.us-east-1.amazonaws.com/daffodil:v1
        ports:
        - containerPort: 4567